import { MigrationInterface, QueryRunner } from 'typeorm';

export class InitialMigration1700000000000 implements MigrationInterface {
  name = 'InitialMigration1700000000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // This migration will be auto-generated by TypeORM
    // Run: npm run migration:generate -- -n InitialMigration
    // Or manually create migrations for your entities
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Rollback logic
  }
}

